apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux kustomizations
   - namespace.yaml
  # Flux kustomizatflux reconcile ks flux-systemions
   - cert-manager/ks.yaml